version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: devops_practice_client
    container_name: client
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: devops_practice_server
    container_name: server
    ports:
      - "5000:5000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: devops_practice_nginx
    container_name: nginx
    depends_on:
      - client
      - server
    ports:
      - "4000:80"
