version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: nutlytical/devops_practice_client
    container_name: client
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: nutlytical/devops_practice_server
    container_name: server
    ports:
      - "5000:5000"
