name: React.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js setup
        uses: actions/setup-node@v2

      - name: Install
        working-directory: ./client
        run: npm install

      - name: Test
        working-directory: ./client
        run: npm run test
