name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build client image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile

      - name: Build server image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile

      - name: Build nginx image
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
